### ISSUE TITLE
SyntaxError: '(' was never closed

### ISSUE THREAD

**Issue by Phyrocycle27** [tas-unn/bypass_keenetic#1]
При запуске скрипта появляется ошибка "SyntaxError: '(' was never closed". Дописав "t)" проблема решается. Исправьте, пожалуйста.

https://github.com/tas-unn/bypass_keenetic/blob/dec6277405582687824ee608af67a5cd50983522/bot.py#L445

**Comment by tas-unn** [comment]
Спасибо! исправлено. Там ещё часть строки добавить надо было
