### ISSUE TITLE
Как проверить упал ли сервис?

### ISSUE THREAD

**Issue by ikocs** [tas-unn/bypass_keenetic#16]
Добрый день.

Внезапно запросы перестали перекидываться через VPN. Бот при этот работал штатно. Помогла перезагрузка роутера. Подскажите, если ситуации повториться, какие логи можно посмотреть?

Файл `/opt/etc/error.log` даже не создан, так что, ошибок бот вроде не посылал.  В чем ещё могла быть проблема?

Использую обход только shadowsocks.

**Comment by tas-unn** [comment]
Попробуйте обновлённую версию https://github.com/ziwork/bypass_keenetic
Да, я тоже замечал такое. Быть может есть смысл  перезагружать роутер ежедневно ночью

**Comment by ikocs** [comment]
> Попробуйте обновлённую версию https://github.com/ziwork/bypass_keenetic
> Да, я тоже замечал такое. Быть может есть смысл  перезагружать роутер ежедневно ночью 

О, попробую обновится тогда. Как раз хотел поддержку WG
