### ISSUE TITLE
twitter unblock

### ISSUE THREAD

**Issue by romikkazan** [tas-unn/bypass_keenetic#2]
За скрипт и список ип адресов для обхода блокировок соц. сетей спасибо, но как же твиттер? Почему его ип адресов нет в этом списке?( Прошу добавить, пожалуйста.

**Comment by romikkazan** [comment]
> За скрипт и список ип адресов для обхода блокировок соц. сетей спасибо, но как же твиттер? Почему его ип адресов нет в этом списке?( Прошу добавить, пожалуйста.

Упс, невнимательно посмотрел, увидел, все есть! Огромное вам спасибо еще раз!

**Comment by romikkazan** [comment]
> > За скрипт и список ип адресов для обхода блокировок соц. сетей спасибо, но как же твиттер? Почему его ип адресов нет в этом списке?( Прошу добавить, пожалуйста.
> 
> Упс, невнимательно посмотрел, увидел, все есть! Огромное вам спасибо еще раз!

Все равно, в твиттере почему-то картинки и видео не подгружаются(
Вероятно, есть еще айпи адреса, попавшие под блок, и отсутствующие в списке

**Comment by romikkazan** [comment]
> > > За скрипт и список ип адресов для обхода блокировок соц. сетей спасибо, но как же твиттер? Почему его ип адресов нет в этом списке?( Прошу добавить, пожалуйста.
> > 
> > 
> > Упс, невнимательно посмотрел, увидел, все есть! Огромное вам спасибо еще раз!
> 
> Все равно, в твиттере почему-то картинки и видео не подгружаются( Вероятно, есть еще айпи адреса, попавшие под блок, и отсутствующие в списке

Я нашел недостающие в вашем списке IP твиттера! Держите:
93.184.220.0/22 (pbs.twimg.com)
192.229.128.0/17 (video.twimg.com)
69.195.160.0/19 (api-23-0-0.twitter.com)

**Comment by romikkazan** [comment]
А вообще, **весь ваш список** можно сократить удалив дублирующиеся IP и использовав CIDR. **Вот он абсолютно весь**, вместе с моими найденными адресами:

104.244.40.0/21, 147.75.208.0/20, 185.89.216.0/22, 31.13.24.0/21, 31.13.64.0/18, 45.64.40.0/22, 66.220.144.0/20, 69.63.176.0/20, 69.171.224.0/19, 74.119.76.0/22, 102.132.96.0/20, 103.4.96.0/22, 129.134.0.0/16, 157.240.0.0/16, 163.70.128.0/17, 163.77.128.0/17, 173.252.64.0/18, 179.60.192.0/22, 185.60.216.0/22, 204.15.20.0/22, 93.184.220.0/22, 192.229.128.0/17, 69.195.160.0/19

**Comment by tas-unn** [comment]
Поправил, спасибо большое!
