### ISSUE TITLE
Telegram id вместо @username

### ISSUE THREAD

**Issue by emerphesis** [tas-unn/bypass_keenetic#4]
Можно ли добавить возможность указывать id вместо @username для строчки usernames.append('Mylogin')

**Comment by tas-unn** [comment]
А что Вы подразумеваете под "ID"?
https://docs.telethon.dev/en/stable/modules/client.html?highlight=from_users%20#module-telethon.client.users
вот тут рассказано про этот метод. Оптимальнее всего оставить username
![image](https://user-images.githubusercontent.com/92320184/200559018-000cc72a-491e-4621-807c-795160737865.png)
