### ISSUE TITLE
Блокировка хостов

### ISSUE THREAD

**Issue by viiy** [tas-unn/bypass_keenetic#5]
Если добавить блокировку хостов (рекламы) будет вообще огонь

**Comment by tas-unn** [comment]
Мне не нравится мысль о подобной блокировке, так как некоторые сайты некорректно отображаются с блокировщиком. Я обычно использую браузерное расширение adblock, но если Вы хотите, то можно https://forum.keenetic.com/topic/8203-adguardhome/ вот тут посмотреть как можно и на роутер поставить.

**Comment by tas-unn** [comment]
> Если добавить блокировку хостов (рекламы) будет вообще огонь
Как я писал выше мне не очень импонирует эта тема, но люди постарались и написали инструкцию: 

https://forum.keenetic.com/topic/14672-%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B0-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%BE%D0%BA-%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BD%D0%B5-%D0%B1%D1%8B%D0%B2%D0%B0%D0%B5%D1%82/?do=findComment&comment=160416
Не проверял, поэтому добавлять поддержку в свой продукт пока не планирую
