### ISSUE TITLE
no-check-certificate wget

### ISSUE THREAD

**Issue by RojerSmith** [tas-unn/bypass_keenetic#6]
Не работает скрипт, wget ругается на no-check-certificate
```
~ # wget https://raw.githubusercontent.com/tas-unn/bypass_keenetic/master/bot.py
 --no-check-certificate -O /opt/etc/bot.py
wget: unrecognized option '--no-check-certificate'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```
Подскажите, куда смотреть. Вроде wget должен быть с ssl, но как его обновить... я чайник если что

**Comment by L719dhh** [comment]
> Добрый день, на сколько я помню, нужно поставить opkg install wget-ssl Отпишитесь если всё окей
Помогло
`opkg remove wget*`
`opkg install wget-ssl`

**Comment by RojerSmith** [comment]
Спасибо, все получилось!
