### ISSUE TITLE
Не работает проверка if (k != len(sortlist))

### ISSUE THREAD

**Issue by L719dhh** [tas-unn/bypass_keenetic#7]
Всегда выдает "Успешно добавлено", даже когда строка существует 

https://github.com/tas-unn/bypass_keenetic/blob/2002cecf24aa0301e1a6e3e086466bad743e970f/bot.py#L173-L176

Всегда выдает "Успешно удалено", даже когда строка отсутствует 

https://github.com/tas-unn/bypass_keenetic/blob/2002cecf24aa0301e1a6e3e086466bad743e970f/bot.py#L203-L206

**Comment by tas-unn** [comment]
исправлено в версии 2.0
